# Generated by Django 5.2.3 on 2025-08-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_temasopaletras_palabratema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaCrucigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DefinicionTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('definicion', models.TextField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definiciones', to='sst.temacrucigrama')),
            ],
        ),
    ]
