# Generated by Django 5.2.3 on 2025-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0003_temacrucigrama_definiciontema'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopaletras',
            name='tamano',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
