# Generated by Django 5.2.3 on 2025-08-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0004_sopaletras_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='crucigrama',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crucigramas', to='sst.temacrucigrama'),
        ),
        migrations.AddField(
            model_name='sopaletras',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sopas', to='sst.temasopaletras'),
        ),
    ]
