# Generated by Django 5.2.3 on 2025-08-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0005_crucigrama_tema_sopaletras_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopaletras',
            name='matriz',
            field=models.TextField(blank=True, help_text='Letras separadas por comas para formar la cuadrícula', null=True),
        ),
    ]
