# Generated by Django 5.2.3 on 2025-09-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0006_sopaletras_matriz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definiciontema',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='movimientoarticular',
            name='pausa',
        ),
        migrations.RemoveField(
            model_name='palabratema',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='registropausa',
            name='pausa',
        ),
        migrations.RemoveField(
            model_name='sopaletras',
            name='pausa',
        ),
        migrations.RemoveField(
            model_name='registropausa',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='sopaletras',
            name='tema',
        ),
        migrations.DeleteModel(
            name='Crucigrama',
        ),
        migrations.DeleteModel(
            name='DefinicionTema',
        ),
        migrations.DeleteModel(
            name='TemaCrucigrama',
        ),
        migrations.DeleteModel(
            name='MovimientoArticular',
        ),
        migrations.DeleteModel(
            name='PalabraTema',
        ),
        migrations.DeleteModel(
            name='PausaActiva',
        ),
        migrations.DeleteModel(
            name='RegistroPausa',
        ),
        migrations.DeleteModel(
            name='SopaLetras',
        ),
        migrations.DeleteModel(
            name='TemaSopaLetras',
        ),
    ]
