# Generated by Django 5.2.3 on 2025-09-10 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0007_remove_definiciontema_tema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='asignada',
        ),
        migrations.RemoveField(
            model_name='campaña',
            name='fecha_asignacion',
        ),
        migrations.AddField(
            model_name='campaña',
            name='evidencia_requerida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaña',
            name='usuarios',
            field=models.ManyToManyField(blank=True, through='sst.CampanaAsignada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampañaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias_campañas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.campaña')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaña',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='campañas', to='sst.grupo'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('abierta', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('campaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst.campaña')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
