# Generated by Django 5.2.3 on 2025-09-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0008_remove_campaña_asignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sst.actividad'),
        ),
        migrations.AddField(
            model_name='campaña',
            name='horarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
