# Generated by Django 5.2.3 on 2025-09-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0009_campaña_actividad_campaña_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('correo', 'Correo Electrónico'), ('web', 'Notificación Web')], default='web', max_length=10),
        ),
    ]
